### ISSUE TITLE
wrong shared lib lookup in archlinux

### ISSUE THREAD

**Issue by nolash** [fltt/dlinkcontrol#1]
```
$ ./configure
checking for pidfile_open in -lutil... no
configure: error: libutil is required
```

On my archlinux, `pidfile_open` seems to be in `-lbsd` not `-lutil`:

```
$ objdump -T /usr/lib/libbsd.so.0 | grep pidfile
000000000000ae10 g    DF .text  00000000000000ef  LIBBSD_0.2  pidfile_write
000000000000afa0 g    DF .text  000000000000002b  LIBBSD_0.9  pidfile_fileno
000000000000af00 g    DF .text  000000000000008a  LIBBSD_0.2  pidfile_close
000000000000b2c0 g    DF .text  00000000000002b8  LIBBSD_0.2  pidfile_open
000000000000af90 g    DF .text  000000000000000e  LIBBSD_0.2  pidfile_remove
$ objdump -T /usr/lib/libutil.so.1 | grep pidfile
$
```

If I edit configure.ac accordingly it works:

```
diff --git a/configure.ac b/configure.ac
index 6ee2bd4..11050df 100644
--- a/configure.ac
+++ b/configure.ac
@@ -27,7 +27,7 @@ AC_CONFIG_MACRO_DIR([m4])
 AM_INIT_AUTOMAKE([-Wall -Werror foreign])
 AC_PROG_CC
 gl_EARLY
-AC_CHECK_LIB([util], [pidfile_open], [],
+AC_CHECK_LIB([bsd], [pidfile_open], [],
              [AC_MSG_ERROR([libutil is required])])
 LIBCURL_CHECK_CONFIG([yes], [7.17.0],
                      [AS_IF([test "x$libcurl_protocol_HTTP" = xyes],
```

**Comment by fltt** [comment]
Hi, thanks for your report!
I've created a new branch [1-wrong-shared-lib-lookup-in-archlinux](https://github.com/fltt/dlinkcontrol/tree/1-wrong-shared-lib-lookup-in-archlinux) to fix the problem.
If you can confirm that it works for you, I'll merge it on master and close the issue.

**Comment by nolash** [comment]
can configure and make with this successfully. thanks.

**Comment by ivanbistrovic** [comment]
Hello, sorry I have to add that this does not work for me. I am on latest _MX Linux 23_ trying to compile the latest source from _dlinkcontrol-1.0.2._ It throws me "_configure: error: could not find pidfile_open function_" and breaks the process. Is it possible that I am missing some development dependencies, I checked in my system and there is at the moment only "_libcurl4-openssl-dev_".

**Comment by fltt** [comment]
Hi!
You have to install the `libbsd` library, although it seems your *Linux* distribution doesn't have it among the available packages.
I guess you have to compile it from source. See [here](https://libbsd.freedesktop.org/wiki/).

**Comment by ivanbistrovic** [comment]
Hi, your advice solved the first problem, thank you for that. But now I have another one. I appended the result from the terminal at the bottom of this article just in case anyone has any idea on what here went wrong. It might be that my Linux distro is not a good ground for building this software. Since you wrote that you made this on BSD system, I think it might be best to install FreeBSD on virtual machine and compile the code there.

I am primarily in search for a way how to change the default DNS server addresses given by the ISP on this USB modem. I have the model V2 which has no D-Link Connection Manager as a separate program like it was on older versions of the firmware where it would be installed from the built-in mass storage device (which would of course only work on Windows OS). But anyway, the latest models have their internal configuration accessible only through a web interface and it has only very basic options.
So I was curious about your program since you wrote that it can extract the DNS addresses given from the ISP, and I thought it will help me find a way how to access this data in the modem and eventually change it. So far I know that the modem offers several protocols to access the settings, like those you mentioned in the description, QMI, RNDIS, CDC_ECM (MBIM?) and I think Serial AT interface. If you have any advices on this topic I would be grateful!

_make_ error:
`Making all in src
make[2]: Verzeichnis „/home/user/Build_Directory/dlinkcontrol-1.0.2/src“ wird betreten
gcc -DHAVE_CONFIG_H -I. -I..  -I../lib -I../lib    -g -O2 -MT dlinkcontrol-dlinkcontrol.o -MD -MP -MF .deps/dlinkcontrol-dlinkcontrol.Tpo -c -o dlinkcontrol-dlinkcontrol.o `test -f 'dlinkcontrol.c' || echo './'`dlinkcontrol.c
gcc -DHAVE_CONFIG_H -I. -I..  -I../lib -I../lib    -g -O2 -MT dlinkcontrol-cJSON.o -MD -MP -MF .deps/dlinkcontrol-cJSON.Tpo -c -o dlinkcontrol-cJSON.o `test -f 'cJSON.c' || echo './'`cJSON.c
mv -f .deps/dlinkcontrol-dlinkcontrol.Tpo .deps/dlinkcontrol-dlinkcontrol.Po
mv -f .deps/dlinkcontrol-cJSON.Tpo .deps/dlinkcontrol-cJSON.Po
gcc  -g -O2 -lcurl -lcurl -o dlinkcontrol dlinkcontrol-dlinkcontrol.o dlinkcontrol-cJSON.o ../lib/libgnu.a -lbsd 
/usr/bin/ld: dlinkcontrol-dlinkcontrol.o: in function `qcmap_post':
/home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:937: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:939: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:941: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:945: undefined reference to `curl_easy_perform'
/usr/bin/ld: /home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:873: undefined reference to `curl_global_init'
/usr/bin/ld: /home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:878: undefined reference to `curl_version_info'
/usr/bin/ld: /home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:904: undefined reference to `curl_easy_init'
/usr/bin/ld: /home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:909: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:912: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:914: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:917: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:919: undefined reference to `curl_easy_setopt'
/usr/bin/ld: dlinkcontrol-dlinkcontrol.o:/home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:922: more undefined references to `curl_easy_setopt' follow
/usr/bin/ld: dlinkcontrol-dlinkcontrol.o: in function `qcmap_post':
/home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:886: undefined reference to `curl_url'
/usr/bin/ld: /home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:891: undefined reference to `curl_url_set'
/usr/bin/ld: /home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:893: undefined reference to `curl_url_set'
/usr/bin/ld: /home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:895: undefined reference to `curl_url_set'
/usr/bin/ld: /home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:897: undefined reference to `curl_url_set'
/usr/bin/ld: dlinkcontrol-dlinkcontrol.o: in function `main':
/home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:2334: undefined reference to `curl_easy_cleanup'
/usr/bin/ld: /home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:2336: undefined reference to `curl_url_cleanup'
/usr/bin/ld: /home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:2337: undefined reference to `curl_global_cleanup'
/usr/bin/ld: dlinkcontrol-dlinkcontrol.o: in function `error_print':
/home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:761: undefined reference to `curl_url_strerror'
/usr/bin/ld: /home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:791: undefined reference to `curl_url_strerror'
/usr/bin/ld: /home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:784: undefined reference to `curl_easy_strerror'
/usr/bin/ld: /home/user/Build_Directory/dlinkcontrol-1.0.2/src/dlinkcontrol.c:755: undefined reference to `curl_easy_strerror'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1498: dlinkcontrol] Fehler 1
make[2]: Verzeichnis „/home/user/Build_Directory/dlinkcontrol-1.0.2/src“ wird verlassen
make[1]: *** [Makefile:1564: all-recursive] Fehler 1
make[1]: Verzeichnis „/home/user/Build_Directory/dlinkcontrol-1.0.2“ wird verlassen
make: *** [Makefile:1484: all] Fehler 2
`

**Comment by fltt** [comment]
It looks like `gcc` can't find the `cURL` library.
What's the output of `ldconfig -p | grep -F libcurl`?
If nothing is output, then I guess the `libcurl4-openssl-dev` only contains the header files.
Try installing `libcurl4-openssl` or whatever package contains the `libcurl.so.4` binary.

As for the DNS, you cannot change the DNS server adresses reported by the DWM-222.
And there's no point doing so -- if you don't want to use them, then just don't.
Years ago changing the DNS servers your system would use was as simple as editing/adding the `nameserver` lines of your `/etc/resolv.conf`.
Now, with the widespread use of `systemd` that's no more that simple.
However the man pages are your friends -- try `man systemd-resolved` or [this wiki page](https://wiki.archlinux.org/title/Systemd-resolved).

**Comment by ivanbistrovic** [comment]
I realized that I had a wrong idea on how DNS works locally, basically I thought that in order to switch to alternative DNS addresses I would have to change them on a device that actually establishes a WAN connection, which would be my DWM-222 in this case. Thanks for clearing it up, I solved this problem.

About the other issue, `ldconfig -p | grep -F libcurl` outputs:
```
libcurl.so.4 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcurl.so.4
libcurl.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libcurl.so
libcurl-gnutls.so.4 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcurl-gnutls.so.4
```
`configure` is passing without any problems but `make` is showing different logs depending on how many times I run it. I tried re-running `make` and every time is different output, some times shorter, some times longer, in some cases even without any visible error, but produces no binaries.
This might be just a platform issue.

**Comment by fltt** [comment]
I agree, it looks like a platform issue.
Specifically, a *GCC* issue -- for some reason the `/lib/x86_64-linux-gnu` directory -- a supposedly "system directory" -- is not included in the library search path.

But you can tell *GCC* to look there for the libraries.
Try again to compile, then when `make` fails, copy the last `gcc` command run, modify it by inserting `-L/lib/x86_64-linux-gnu` before the `-lcurl`, `cd` into the `src` directory and execute the edited command.
For example, using the `make` command output you pasted above, that would result in the following commands:

```
cd /home/user/Build_Directory/dlinkcontrol-1.0.2/src
gcc -g -O2 -L/lib/x86_64-linux-gnu -lcurl -o dlinkcontrol dlinkcontrol-dlinkcontrol.o dlinkcontrol-cJSON.o ../lib/libgnu.a -lbsd
```

> **NOTE:** I don't know why the `-lcurl` is duplicated,  but there's no need to be. Maybe there is some issue with the `LIBCURL_CHECK_CONFIG` *M4* macro I use to locate the *cURL* library.

**Comment by ivanbistrovic** [comment]
I tried with the above command, because I had the same make output. It results in repeating the same output again, beginning with the line `/usr/bin/ld: dlinkcontrol-dlinkcontrol.o: in function `qcmap_post':`.
I am preparing already to install FreeBSD in VM to give it a try there. I saw that in the installation process it asks for installing some optional packages like Tests and some other components. For any advice on setting up FreeBSD as a build machine, I would be thankful.

**Comment by fltt** [comment]
To compile `dlinkcontrol` on a *FreeBSD* machine you don't need any optional component nor additional package -- a minimal installation will do.
In this scenario, `dlinkcontrol` would be compiled against `libfetch` (*FreeBSD* native HTTP library).

However, `libfetch` is not as good as `libcurl`, so, if you have problem with `libfetch`, try installing `libcurl` (with `pkg install curl`) then recompile again `dlinkcontrol`.
