### ISSUE TITLE
Some support?

### ISSUE THREAD

**Issue by ViBE-HU** [fltt/dlinkcontrol#2]
Sorry for writing here but Google just randomly popped up your repo. I have two DWM-222 and one is sadly bricked. I though I might find something here. But now I see no luck here.

And now I also want to understand how your tool work. What I know that the A2 EU variant use QMI protocol with the 2.0.1 firmware. If you update it to 2.0.2 it will use RNDIS. I rarely use RNDIS cause I hate NAT and prefer manual setup. As I understand your tool can switch the protocol on the modem.

But some details are not clear for me:
- which firmware versions are compatible?
- which hardware versions are compatible?
- can I change the protocol after the 2.0.2 EU update?
- is the protocol change permanent (till I change it again)?

**Comment by fltt** [comment]
Hello!
As far as I know -- but I might be wrong -- both releases 2.0.1 and 2.0.2, support all protocols, i.e., QMI, RNDIS and CDC-ECM.
However, on *FreeBSD*, which has no drivers for the QMI protocols, I could not get the DWM-222 work with the other two protocols.
Before tossing the DWM-222 away, I tried upgrading it to version 2.0.2, and it worked.

So, back to your questions:

- `dlinkcontrol` doesn't switch protocol, on *FreeBSD* this is done through the `camcontrol eject` and the `usbcontrol set_config` commands run from the `devd` subsystem
- both firmware / hardware should be compatible, but only after you switch protocol to RNDIS or CDC-ECM
- whenever the DWM-222 is plugged-in or reset, the active protocol is QMI; to switch to the RNDIS protocol, send the eject command and to switch to the CDC-ECM protocol, from RNDIS, set the USB active configuration to 1
- to switch from CDC-ECM back to RNDIS you just set the USB active configuration to 0, but to switch back to QMI I guess you have to reset or unplug/replug it

Again, take all I said with a grain of salt -- it's been a while since I last used this device.
If in doubt, experiment: `camcontrol` and `usbcontrol` -- or the equivalent tools available in your OS -- should be safe to use.
I used them a lot on the DWM-222 without problems.

**Comment by ViBE-HU** [comment]
Thanks for the clarification. I forgot to mention that I mostly use my modems in Linux environments. I have some traveller routers with WRT/Gargoyle and I use my modems with those. Even if the ping is noticeable crap with the DWM-222 I tried to find some a reason to use it. The only advantage as I see is the higher bandwidth (I mean my Alcatel and Huawei modems are slower with other protocols). But depending on the host OS I have to do some workarounds to get the QMI protocol work. Of course If I can already switch somehow permanently to one and another it would be way easier to use these modems IF the host recognise them.

And now as I understand this tool cannot be used on WRT routers. Btw is ECM better? Never heard of it.

**Comment by fltt** [comment]
AFAIK, RNDIS and CDC-ECM are more or less equivalent.
The difference being the OS they were conceived for, i.e., RNDIS for Windows and CDC-ECM for the rest of the world.

However -- if I remember correctly -- I was able to at least configure the DWM-222 on a *Linux* machine, using some QMI tool, when still trying to make it work on *FreeBSD*.
`qmicli` maybe?
